-- 2세대
WITH TWO_GENER AS (
    SELECT ID, PARENT_ID
        FROM ECOLI_DATA
        WHERE PARENT_ID IN (SELECT ID FROM ECOLI_DATA WHERE PARENT_ID IS NULL)
    )

-- 3세대
SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IN (SELECT ID FROM TWO_GENER);
