-- 코드를 작성해주세요
SELECT T1.ID, T1.GENOTYPE, T2.GENOTYPE AS PARENT_GENOTYPE
FROM (SELECT ID, PARENT_ID, GENOTYPE
     FROM ECOLI_DATA) AS T1
     JOIN
     (SELECT ID, GENOTYPE
     FROM ECOLI_DATA) AS T2
ON T1.PARENT_ID = T2.ID AND (T1.GENOTYPE & T2.GENOTYPE) = T2.GENOTYPE
ORDER BY T1.ID