SELECT A.APNT_NO, A.PT_NAME, A.PT_NO, A.MCDP_CD, B.DR_NAME, A.APNT_YMD
    FROM (
        SELECT AP.APNT_YMD, BP.PT_NAME, AP.PT_NO, AP.MCDP_CD, AP.APNT_NO, AP.MDDR_ID, AP.APNT_CNCL_YN
        FROM 
            APPOINTMENT AS AP
            JOIN PATIENT AS BP
            ON AP.PT_NO = BP.PT_NO
    ) AS A
    JOIN DOCTOR AS B
    ON A.MDDR_ID = B.DR_ID
    
    WHERE DATE_FORMAT(A.APNT_YMD, "%Y-%m-%d") = "2022-04-13"
            AND A.MCDP_CD LIKE "CS" AND A.APNT_CNCL_YN LIKE "N"
    ORDER BY A.APNT_YMD;