SELECT CATEGORY, MAX(PRICE) PRICE, PRODUCT_NAME 
FROM FOOD_PRODUCT
WHERE PRICE IN(SELECT MAX(PRICE) FROM FOOD_PRODUCT GROUP BY CATEGORY)
GROUP BY CATEGORY
HAVING CATEGORY IN ('과자','국','김치','식용유')
ORDER BY PRICE DESC;
